In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("Customer dataset.csv")

In [6]:
df.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,26-07-2021,http://www.shea.biz/
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,24-06-2021,http://www.pena-cole.com/
2,3,d794Dd48988d2ac,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,001-680-204-8312,justincurtis@pierce.org,05-04-2020,http://www.booth-reese.biz/
3,4,3b3Aa4aCc68f3Be,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,048.779.5035x9122,adeleon@hubbard.org,29-11-2020,http://www.hebert.com/
4,5,D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,22-04-2022,http://merritt.com/

In [7]:
df.shape

(1000, 12)

In [8]:
df.columns

Index(['Index', 'Customer Id', 'First Name', 'Last Name', 'Company', 'City',
       'Country', 'Phone 1', 'Phone 2', 'Email', 'Subscription Date',
       'Website'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              1000 non-null   int64
 1   Customer Id        1000 non-null   object
 2   First Name         1000 non-null   object
 3   Last Name          1000 non-null   object
 4   Company            1000 non-null   object
 5   City               1000 non-null   object
 6   Country            1000 non-null   object
 7   Phone 1            1000 non-null   object
 8   Phone 2            1000 non-null   object
 9   Email              1000 non-null   object
 10  Subscription Date  1000 non-null   object
 11  Website            1000 non-null   object
dtypes: int64(1), object(11)
memory usage: 93.9+ KB

In [10]:
df.describe(include="all")

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
count,1000.000000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000
unique,NaN,1000,536,622,992,983,240,1000,1000,1000,608,973
top,NaN,51732B5b2328015,Larry,Waters,Mercado PLC,Deniseburgh,Liechtenstein,-5366,814-860-0941x057,owarner@velasquez.info,29-04-2022,http://www.tapia.com/
freq,NaN,1,6,7,2,2,12,1,1,1,5,3
mean,500.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,288.819436,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,250.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,500.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,750.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1000.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
#Duplicate Record Validation
df.duplicated().sum()

np.int64(0)

In [12]:
#Display duplicate rows
df[df.duplicated()]

Empty DataFrame
Columns: [Index, Customer Id, First Name, Last Name, Company, City, Country, Phone 1, Phone 2, Email, Subscription Date, Website]
Index: []

In [13]:
#Remove duplicate rows
df_cleaned = df.drop_duplicates()

In [14]:
#Verify duplicates were removed
df_cleaned.duplicated().sum()

np.int64(0)

In [15]:
#Data Validation Checks
#Missing Values
df_cleaned.isnull().sum()

Index                0
Customer Id          0
First Name           0
Last Name            0
Company              0
City                 0
Country              0
Phone 1              0
Phone 2              0
Email                0
Subscription Date    0
Website              0
dtype: int64

In [16]:
#Duplicate Customer IDs
df_cleaned["Customer Id"].duplicated().sum()

np.int64(0)

In [17]:
df_cleaned[df_cleaned["Customer Id"].duplicated(keep=False)]

Empty DataFrame
Columns: [Index, Customer Id, First Name, Last Name, Company, City, Country, Phone 1, Phone 2, Email, Subscription Date, Website]
Index: []

In [18]:
#Email Validation
invalid_email = df_cleaned[
    ~df_cleaned["Email"].astype(str).str.contains("@", na=False)
]

invalid_email

Empty DataFrame
Columns: [Index, Customer Id, First Name, Last Name, Company, City, Country, Phone 1, Phone 2, Email, Subscription Date, Website]
Index: []

In [20]:
#Phone Number Validation
phone_digits = (
    df_cleaned["Phone 1"]
    .astype(str)
    .str.replace(r"\D", "", regex=True)
)

invalid_phone = df_cleaned[
    (phone_digits.str.len() < 7) |
    (phone_digits.str.len() > 15)
]

invalid_phone

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
4,5,D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,22-04-2022,http://merritt.com/
5,6,8aaa5d0CE9ee311,Marissa,Gamble,Cherry and Sons,Webertown,Sudan,001-645-334-5514x0786,(751)980-3163,katieallison@leonard.com,17-11-2021,http://www.kaufman.org/
13,14,aBd960429ecd363,Ryan,Li,"Hooper, Cross and Holt",Batesville,Liechtenstein,001-119-787-0125x4500,001-477-254-3645,lmassey@duke.com,06-03-2021,http://nunez.com/
16,17,41d0201DcF028b5,Sophia,Mathis,Richard-Velasquez,Toddhaven,Switzerland,001-858-762-7896x916,274-147-4185x15182,brockmason@faulkner-may.com,23-01-2020,http://www.vaughn.com/
23,24,c5CB6C5bFB91fdC,Darius,Benitez,Giles LLC,Mejiashire,Jersey,+1-797-864-3151x25142,139-216-5379x6030,garrettdurham@olsen.com,28-02-2022,https://washington.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
983,984,Ff2d5a11Cc04713,Lisa,Yates,Blair Group,Valeriehaven,United States Minor Outlying Islands,001-932-182-2660x0209,-2542,beverlypreston@cook-fuller.info,29-07-2020,https://huber.com/
987,988,e4D86CB5ED2a7c6,Cynthia,Greene,Choi Ltd,Hancockchester,Ghana,001-241-633-1236x0619,+1-816-826-1774x7691,chad71@blankenship.org,02-12-2020,https://bridges.info/
991,992,aB56cEcDBa37C34,Kiara,Moon,Olsen-Morse,Hesterburgh,American Samoa,001-414-102-0839x208,663-698-9231x994,paynesteven@nguyen-richardson.com,05-12-2020,http://yang.org/
995,996,FbcCaF483aFaFAE,Diana,Monroe,Bass-Wilson,Lake Jacksonmouth,Guatemala,+1-171-715-9766x54993,(489)413-7296x32807,cassidymercado@bonilla.com,09-01-2022,http://castro.net/
999,1000,51732B5b2328015,Dominic,Duran,Durham LLC,East Wendy,British Indian Ocean Territory (Chagos Archipe...,-5366,814-860-0941x057,owarner@velasquez.info,09-12-2021,http://www.cox.com/

In [22]:
#Website Validation
invalid_website = df_cleaned[
    ~df_cleaned["Website"].astype(str).str.contains(
        r"\.",
        regex=True,
        na=False
    )
]

invalid_website

Empty DataFrame
Columns: [Index, Customer Id, First Name, Last Name, Company, City, Country, Phone 1, Phone 2, Email, Subscription Date, Website]
Index: []

In [23]:
#First Name Validation
df_cleaned["First Name"].isnull().sum()

np.int64(0)

In [24]:
#Country Validation
df_cleaned["Country"].nunique()

240

In [25]:
#Final Dataset Checks
#Check missing values again
df_cleaned.isnull().sum()

Index                0
Customer Id          0
First Name           0
Last Name            0
Company              0
City                 0
Country              0
Phone 1              0
Phone 2              0
Email                0
Subscription Date    0
Website              0
dtype: int64

In [26]:
#Check duplicates again
df_cleaned.duplicated().sum()

np.int64(0)

In [27]:
#Check Customer ID uniqueness
df_cleaned["Customer Id"].is_unique

True

In [28]:
#View the cleaned data
df_cleaned.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/
2,3,d794Dd48988d2ac,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,001-680-204-8312,justincurtis@pierce.org,2020-04-05,http://www.booth-reese.biz/
3,4,3b3Aa4aCc68f3Be,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,048.779.5035x9122,adeleon@hubbard.org,2020-11-29,http://www.hebert.com/
4,5,D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,2022-04-22,http://merritt.com/

In [29]:
#Save Cleaned Dataset
df_cleaned.to_csv(
    "cleaned_customer_dataset.csv",
    index=False
)